### ISSUE TITLE
Most functions should return AWS.Request objects

### ISSUE THREAD

**Issue by Gaelan** [ingenieux/aws-sdk-typescript#1]
Most functions in the AWS SDK return `AWS.Request`s, but they are currently being typed as just returning `void`. This would be good to fix at some point.

**Comment by DmitryEfimenko** [comment]
+1

Awesome work!

**Comment by enicholson** [comment]
PR here: https://github.com/ingenieux/aws-sdk-typescript/pull/5

**Comment by enicholson** [comment]
@Gaelan, should be fixed now. Let me know what you think.
