### ISSUE TITLE
Last commit broke the definitions 

### ISSUE THREAD

**Issue by Bnaya** [ingenieux/aws-sdk-typescript#10]
Look at
https://github.com/ingenieux/aws-sdk-typescript/commit/59d10934d44d8afc50b8a04c9a3e690a0dee0238#commitcomment-16823167

**Comment by aldrinleal** [comment]
It is intentional, because there's a same named class - with a different purpose - on aws-sdk-common.d.ts. Do you suggest any workaround?

**Comment by Bnaya** [comment]
Thanks for the fix!
