### ISSUE TITLE
Where is AWS.DynamoDB.DocumentClient?

### ISSUE THREAD

**Issue by wutali** [ingenieux/aws-sdk-typescript#12]
I wanna use this DocumentClient to fetch and save document with DynamoDB. But looks like there are no definition for it.

**DocumentClient**
http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html

**Comment by aldrinleal** [comment]
The AWS SDK has basically four parts. Of those, I'll explain how we handle it:
- Lower level primitves (we don't anything, besides the content of what used to be aws-sdk-common.d.ts)
- For each service, it is mostly described with a json file (we do it quite well!)
- On some services, there are some extra methods added via Extend. We add, but we ignore each and every type signature (see #2)
- There are 'value-added' namespaces. We currently don't do anything

You hit the 4th case. A solution would be to send us a patch augmenting the AWS.DynamoDB.DocumentClient features

Thank you

**Comment by wutali** [comment]
I wrote a small code to detect 'value-added' namespaces you said.

```
diff --git a/app/src/app.ts b/app/src/app.ts
index 18bda8b..bedf278 100644
--- a/app/src/app.ts
+++ b/app/src/app.ts
@@ -91,6 +91,7 @@ function readCustomCode() {
   var expr = path.join(sdkDir, '../lib/services/**/*.js')

   var paths = glob.sync(expr)
+  paths = paths.concat(glob.sync(path.join(sdkDir, '../lib/dynamodb/*.js')))

   var methodsToAdd: any = {}

@@ -100,9 +101,16 @@ function readCustomCode() {
       var ast = esprima.parse(src)

       var matcher = jsstana.createMatcher("(call (lookup AWS.util.update) ? ?)")
+      var matcher2 = jsstana.createMatcher("(assign = AWS.DynamoDB.DocumentClient ?)")

       estraverse.traverse(ast, {
         enter: function(n: any) {
+          if (matcher2(n)) {
+            console.log('FOUND!!')
+            var classname = escodegen.generate(n.left).replace(/AWS\.(\w+)\.(\w+)/, "$1");
+            var methodList = n.right.arguments[0].properties.map(function(x: any) { return x.key.name });
+            methodsToAdd['DynamoDB'][classname] = methodList; // This line has a problem.
+          }
           if (matcher(n)) {
             var classname = escodegen.generate(n.arguments[0]).replace(/AWS\.(\w+)\.prototype/, "$1")
```

This code finds assignments adding a new object into DynamoDB namespace. But I have to implement more logic to enter DynamoDB namespace and add DocumentClient into it.

**Comment by aldrinleal** [comment]
I ended up writing a stub myself. Can you look at it now?
