### ISSUE TITLE
How to set region and lambda apiversion

### ISSUE THREAD

**Issue by nirmalgoswami** [ingenieux/aws-sdk-typescript#19]
Hello,

thanks for making this.i am trying to set region and lambda apiversions

so far i tried like this 

```
import AWS = require('aws-sdk');
....
....
AWS.config.region = 'us-west-2';

AWS.config.apiVersions = {
            lambda: '2015-03-31'
        };
```

but i i got following error
`Error: Missing region in config(…)`

Thank you 

CC @aldrinleal

**Comment by aldrinleal** [comment]
Last time I did:

``` typescript
///<reference path="../typings/tsd.d.ts"/>

import {config as AWSConfig, Credentials, Lambda} from "aws-sdk";

var lambda = new Lambda({
  credentials: new Credentials(accessKeyId || this.accessKeyId, secretAccessKey || this.secretAccessKey),
  region: region || this.region
});
```

Hope it helps

**Comment by aldrinleal** [comment]
btw, please refrain from doing CC. As it looked from your public profile, its your behaviour, but remind that just as you've got urgent needs and jobs to do, so do I - and guess what, I'm working as well :)

(tl;dr: not only you didn't need to do a cc, you already made a very bad entrance)

**Comment by nirmalgoswami** [comment]
@aldrinleal Thanks for answer,
sorry if i made mistake in asking question but you are senior and i am always taking word from senior as positive :) i will keep your point in mind thank you

**Comment by nirmalgoswami** [comment]
It Worked ! 

Thank you @aldrinleal
