### ISSUE TITLE
S3.getSignedUrl missing

### ISSUE THREAD

**Issue by DmitryEfimenko** [ingenieux/aws-sdk-typescript#2]
I'm not sure how this project works (where you get the JSON from which you generate typings), but I noticed the `aws-s3.d.ts` in the `output` folder is missing definition for `getSignedUrl` method.

[Here are docs for this method.](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property)

**Comment by enicholson** [comment]
Some of the services have methods like this that are implemented directly in the aws-sdk-js codebase rather than being generated from the json definitions that aws-sdk-typescript uses.

I'm thinking the easiest thing to do is to manually define them somewhere where the generated & manual definitions can be merged together.

**Comment by aldrinleal** [comment]
I added source level scanning - It reveals the missing methods, but the metadata information is lost, at least. I wonder if having a separate file with the manually-written signatures (+ types) would help on a later moment

**Comment by aldrinleal** [comment]
@DmitryEfimenko can you confirm its fine now?

**Comment by DmitryEfimenko** [comment]
It looks like `getSignedUrl()` is there now, but just like you said, no information about params.

Have no idea how to handle this issue (if we want to), but in case it helps anything, previously I manually added this method like so:

inside `export class S3 extends Service { }`

``` js
getSignedUrl(operation: string, params: S3.GetSignedUrl, callback: (err: any, url: string) => void): void;
```

inside `export module S3 { }`

``` js
export interface GetSignedUrl {
    Bucket: BucketName;
    Key: ObjectKey;
    Expires?: number;
    ResponseContentDisposition?: string;
    ResponseContentType?: string;
    PartNumber?: number;
    UploadId?: string;
}
```
