### ISSUE TITLE
Why use this package instead of the dt-aws-sdk one?

### ISSUE THREAD

**Issue by StefH** [ingenieux/aws-sdk-typescript#22]

**Comment by aldrinleal** [comment]
[As seen on dt's Repo](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/7458)

**Comment by StefH** [comment]
Clear. However you mention tsd. Isn't that replace by typings?

**Comment by aldrinleal** [comment]
It is - look at the tickets.
