### ISSUE TITLE
AWS.SES module is missing

### ISSUE THREAD

**Issue by DmitryEfimenko** [ingenieux/aws-sdk-typescript#8]
There is a Simple Email Service (SES) that is missing in from the type definitions.
Here is a [link to its api](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/SES.html)
It'd be great if it was added.

**Comment by aldrinleal** [comment]
[this guy](https://github.com/ingenieux/aws-sdk-typescript/blob/master/output/typings/aws-email.d.ts)?

**Comment by DmitryEfimenko** [comment]
my bad. I was searching for "SES" instead of "Emails"
Closing this.

**Comment by aldrinleal** [comment]
See #2 as well please

(btw, update - I just published an updated release with moar changes)

**Comment by DmitryEfimenko** [comment]
great, I'll get latest and see if anything broke.
Will take a look at #2 in a sec.
