### ISSUE TITLE
typings support: is there a way to install it via typings?

### ISSUE THREAD

**Issue by Bnaya** [ingenieux/aws-sdk-typescript#9]

**Comment by Bnaya** [comment]
I've found a way to do so, you need to install the wished files one by one, and the files it reference.
Lets say i want `aws-s3.d.ts`
that references `aws-sdk-common.d.ts`  

I will do

```
typings i aws-sdk-common=https://github.com/ingenieux/aws-sdk-typescript/raw/59d1093/output/typings/aws-sdk-common.d.ts -A
```

and 

```
typings i aws-sdk-s3=https://github.com/ingenieux/aws-sdk-typescript/raw/59d1093/output/typings/aws-sdk-s3.d.ts -A
```

on the typings.json it will look like:

```
...
  "ambientDependencies": {
    "aws-sdk-common": "https://github.com/ingenieux/aws-sdk-typescript/raw/59d1093/output/typings/aws-sdk-common.d.ts",
    "aws-sdk-s3": "https://github.com/ingenieux/aws-sdk-typescript/raw/59d1093/output/typings/aws-s3.d.ts",
...
```

**Important**: the 59d1093 in the URL is the commit hash, to lock the file to specific commit. it can be also branch (like master but then it might change without notice) or tag

**Comment by aldrinleal** [comment]
I have optimized it a little, so just typing:

```
$ typings i aws-sdk=github:ingenieux/aws-sdk-typescript --save-dev --verbose
```

Should do the trick. It also fixes the cognito stuff as well.

**Comment by Bnaya** [comment]
awesome, Thanks!
I think that you can set the name in the typings.json to aws-sdk and then you won't need to specify the name on install

**Comment by aldrinleal** [comment]
I'm a noob when it comes to typings. Can you help me figure it out?

## 

-- Aldrin Leal, aldrin@leal.eng.br / http://about.me/aldrinleal

**Comment by Bnaya** [comment]
check the pr,
I'm also noob in all of the typescript things,
I will check what is the proper way to publish it to the typings registry
